### ISSUE TITLE
Transition property name change

### ISSUE THREAD

**Issue by Nuklon** [thednp/shorty#1]
https://github.com/thednp/shorter-js/commit/c9b2686d9cbb0cd8becdc37c5bc30719a3b65173

This changed the name of transitionProperty from (webkit)Transition**Property** to (webkit)Transition, this breaks transitions in Firefox.
With the previous one checking for transition-property: none; it worked OK.

**Comment by thednp** [comment]
That fixes Firefox, but breaks all others :)

**Comment by Nuklon** [comment]
Transitions work for me correctly with this in Chromium?

**Comment by thednp** [comment]
Yes, however, the new `getElementStyle` didn't work, so I had to fix it.

**Comment by Nuklon** [comment]
@thednp Transitions are broken again in Firefox, and Chrome is now also broken. 0.2.23 is the last version that has working transitions in both browsers.

**Comment by thednp** [comment]
The [latest version](https://github.com/thednp/shorter-js/blob/master/src/strings/transitionProperty.js) is fine, perhaps you forgot to update? We're now at `"version": "0.3.0alpha23"`, so I'm experimenting some improvements here and there, fine tuning everything before 0.3.0 release.

**Comment by Nuklon** [comment]
0.2.24 is broken, I can't upgrade to 0.3 beta yet until bootstrap.native is updated :)

**Comment by thednp** [comment]
So test both shorter and bsn, provide feedback and let's get them to stable release then.

**Comment by Nuklon** [comment]
Is the 4.1 alpha of BSN compatible with the beta here? There are so many changes 😊

**Comment by thednp** [comment]
Yesss, many changes, but the two are head to head latest to latest.

**Comment by thednp** [comment]
It so happens that after each release, a lot of new issues reported, but very few test pre-released code :D

**Comment by Nuklon** [comment]
Thanks, I hope to have some time next week to try it out 👍
