### ISSUE TITLE
The package version '2.0.0alpha22' is not a valid SemVer 2.0.0 version

### ISSUE THREAD

**Issue by MuellerNicolas** [thednp/shorty#9]
Hello @thednp,

When executing `npm i` the following error message occurs:
```bash
npm ERR! code E400
npm ERR! 400 Bad Request - GET https://private-registry.xy/DefaultCollection/_packaging/PublicFeed/npm/registry/@thednp/shorty/-/shorty-2.0.0-alpha22.tgz - The package version '2.0.0alpha22' is not a valid SemVer 2.0.0 version
```

I suspect the missing dash in the [package.json-file of your package](https://www.npmjs.com/package/@thednp/shorty?activeTab=code): `"version": "2.0.0alpha22"` to be the problem.

Sidenotes:
- I am using private npm registry
- I must admit, that i have no clue which of my packages in my `package.json` has a dependency to your package, but I noticed that `@thednp/shorty` has a sharp increases in downloads starting from 2023-11-14.
The error occured when I updated my angular version from 14 to 15, but it could be one of many updated packages (aside from angular-packages).

Thank you very much for your support :)

**Comment by MuellerNicolas** [comment]
Edit: I just found out, that my project has a dependency to `@compodoc/compodoc`, which in turn has a dependency to `bootstrap.native`, which is dependent on `@thednp/shorty`.

Removing `@compodoc/compodoc` fixes the install failing issue for me.

Therefore I think the issue is related to `2.0.0alpha22`

**Comment by thednp** [comment]
Will review and solve this asap. Thanks

**Comment by manneymc** [comment]
Thanks @MuellerNicolas ... owe you one ;-)

in our case we have a azure devops artifacts registry with an up-stream feed to https://registry.npmjs.org/  , that all our local devs + build pipelines connect to to get their packages from

when our registry tries to download the package, it fails with the following error

**_The package version '2.0.0alpha22' is not a valid SemVer 2.0.0 version_**


compodoc was used in our pipeline to generate documentation....  so caused a couple of hours of chaos, until problem was identified,  but  we have commented out pipeline steps that were using it and now back up and running👍😅

**Comment by alswinehartMRI** [comment]
I have a feeling you're about to get flooded with this issue. I am also experiencing it. using compodoc as well.

**Comment by m-caboche** [comment]
Exact same issue here. I've submitted a PR which I think should do the trick of fixing the issue.

**Comment by thednp** [comment]
V2.0.0 is now LIVE.

**Comment by alswinehartMRI** [comment]
This fix doesn't change anything in compodoc's current version, but downgrading to compodoc 1.0 removed the error for me.

**Comment by thednp** [comment]
> This fix doesn't change anything in compodoc's current version, but downgrading to compodoc 1.0 removed the error for me.

They need to update the deps.
